### ISSUE TITLE
Status doesn't update when controlling the same GE dimmer with a GE keypad controller

### ISSUE THREAD

**Issue by cben0ist** [jensmoes/Niffler#3]
Hi all,

It's not really an issue but a new use case.

I control 2 GE dimmers (these ones: http://www.zwaveproducts.com/shop/brands/ge/z-wave-plug-in-smart-dimmer) with a GE keypad controller (this one: https://jascoproducts.com/sites/default/files/product/manuals/45631-Manual-Eng.pdf)
I have a razberry controller with the latest zway smarthome UI 

When pressing the button on the GE dimmers, Nifflers update the UI as expected.
When pressing the keypad controller, the dimmers turn on or off as expected but the UI is not updated.

Is there any way to niffle the dimmers after any keypad button is pressed ?

Thank you

**Comment by jensmoes** [comment]
What probably happens, or doesn't, is the dimmer is not sending out a NIF when controlled by the keypad controller. You would need some other way of indicating to the Razberry a local change has occurred. I am not sure there is any easy/cheap solution for this beyond using a dimmer that sends out unsolicited reports at all changes.

**Comment by cben0ist** [comment]
OK, thanks for the fast answer !
Let me know if there is anything I can check t confirm that. Are there some specific logs I should check while using the keypad for example ?
Thank you

**Comment by jensmoes** [comment]
You should see a log entry with ".data.nodeInfoFrame like in this [example](http://forum.z-wave.me/viewtopic.php?f=3424&t=21688#p56759) matching the device ID of the device sending the NIF

**Comment by cben0ist** [comment]
Yep, I can definitely see that in the log when pressing the dimmer button. But no log when using the remote. I guess there is nothing I can do with that remote...
Thanks !
